# Generated by Django 3.0.6 on 2020-06-17 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tx_hash', models.CharField(max_length=400, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=50)),
                ('type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=250)),
                ('summary', models.CharField(choices=[('send', 'send'), ('receive', 'receive')], max_length=250)),
                ('platform', models.CharField(choices=[('luno', 'luno'), ('coinbase', 'coinbase'), ('axemo', 'axemo'), ('blockchain', 'blockchain')], default='blockchain', max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'successful'), ('failed', 'failed')], default='pending', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DebitTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tx_hash', models.CharField(max_length=400, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=50)),
                ('type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=250)),
                ('summary', models.CharField(choices=[('send', 'send'), ('receive', 'receive')], max_length=250)),
                ('platform', models.CharField(choices=[('luno', 'luno'), ('coinbase', 'coinbase'), ('axemo', 'axemo'), ('blockchain', 'blockchain')], default='blockchain', max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('destination', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'successful'), ('failed', 'failed')], default='pending', max_length=200)),
            ],
        ),
    ]
