# Generated by Django 3.0.6 on 2020-06-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_transactions', '0002_auto_20200617_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='debittransaction',
            name='user',
            field=models.CharField(default='test', max_length=400),
        ),
        migrations.AlterField(
            model_name='debittransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=200),
        ),
    ]
