# Generated by Django 3.0.6 on 2020-06-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_transactions', '0003_auto_20200619_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debittransaction',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
