# Generated by Django 3.0.6 on 2020-06-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_transactions', '0004_auto_20200619_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debittransaction',
            name='summary',
        ),
    ]
