# Generated by Django 3.0.6 on 2020-06-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_transactions', '0007_debittransaction_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='debittransaction',
            name='resolve',
            field=models.BooleanField(default=False),
        ),
    ]
