# Generated by Django 3.0.6 on 2020-06-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_transactions', '0008_debittransaction_resolve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debittransaction',
            old_name='platform',
            new_name='route',
        ),
        migrations.AddField(
            model_name='debittransaction',
            name='currency',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('LTC', 'LTC'), ('BCH', 'BCH'), ('NGN', 'NGN')], default='BTC', max_length=250),
        ),
    ]
