# Generated by Django 3.0.6 on 2020-06-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_transactions', '0012_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debittransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
