# Generated by Django 3.0.6 on 2020-06-23 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_transactions', '0014_address_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='date',
            new_name='date_created',
        ),
    ]
