# Generated by Django 3.0.6 on 2020-06-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_transactions', '0015_auto_20200623_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='currency',
            field=models.CharField(max_length=250),
        ),
    ]
