# Generated by Django 3.0.6 on 2020-06-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='primary_down_lines',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='qqfabzafpx', max_length=250),
        ),
        migrations.AlterField(
            model_name='agent',
            name='referral_link',
            field=models.CharField(default='http://127.0.0.1:8000/home/register/iocenmhjuv', max_length=250),
        ),
        migrations.AlterField(
            model_name='agent',
            name='secondary_down_lines',
            field=models.TextField(default=[]),
        ),
    ]
