# Generated by Django 3.0.6 on 2020-06-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_auto_20200624_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='total_down_lines',
            new_name='total_primary_down_lines',
        ),
        migrations.AddField(
            model_name='agent',
            name='total_secondary_down_lines',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='hbgdtrwwzw', max_length=250),
        ),
        migrations.AlterField(
            model_name='agent',
            name='referral_link',
            field=models.CharField(default='http://127.0.0.1:8000/home/register/sdmnvjccuv', max_length=250),
        ),
    ]
