# Generated by Django 3.0.6 on 2020-06-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0003_auto_20200624_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='uwwghsuebr', max_length=250),
        ),
        migrations.AlterField(
            model_name='agent',
            name='referral_link',
            field=models.CharField(default='http://127.0.0.1:8000/home/register/diykmmqgpe', max_length=250),
        ),
    ]
