# Generated by Django 2.1.4 on 2020-06-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0005_auto_20200625_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='referral_code',
            field=models.CharField(default='vmwjgcsccv', max_length=250),
        ),
    ]
