# Generated by Django 3.0.6 on 2020-06-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='agent_status',
            field=models.CharField(default='level 0', max_length=400),
        ),
    ]
