# Generated by Django 3.0.6 on 2020-06-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200621_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='bitcoin_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
