# Generated by Django 3.0.6 on 2020-06-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200621_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='bitcoin_cash_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='etherum_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usersdata',
            name='litecoin_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
