# Generated by Django 3.0.6 on 2020-06-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200622_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='pin',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
