# Generated by Django 3.0.6 on 2020-06-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_usersdata_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='pin',
            field=models.CharField(default='0000', max_length=5),
        ),
    ]
