# Generated by Django 3.0.6 on 2020-06-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200624_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='pin',
            field=models.CharField(default='9af15b336e6a9619928537df30b2e6a2376569fcf9d7e773eccede65606529a0', max_length=200),
        ),
    ]
