# Generated by Django 3.0.6 on 2020-07-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200624_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='local_currency_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='vault_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
