# Generated by Django 3.0.6 on 2020-06-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_history', '0003_auto_20200621_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.CharField(default='{}', max_length=400),
        ),
    ]
