# Generated by Django 3.0.6 on 2020-06-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_history', '0005_thistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='THistory',
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.CharField(default='UNKNOWN', max_length=400),
        ),
    ]
