# Generated by Django 3.0.6 on 2020-06-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_history', '0007_auto_20200621_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='history',
        ),
        migrations.AddField(
            model_name='history',
            name='bch_history',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='history',
            name='btc_history',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='history',
            name='eth_history',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='history',
            name='ltc_history',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='history',
            name='ngn_history',
            field=models.TextField(default='{}'),
        ),
    ]
